[platformio]
; Choose which one to build by default, or build all
default_envs = esp32_wroom, esp32_s3_zero, esp32_c3_zero

; ----------------------------------------------------------------
; COMMON CONFIGURATION (Shared by all boards)
; ----------------------------------------------------------------
[env]
platform = espressif32
framework = arduino

upload_speed = 921600
monitor_speed = 115200
monitor_filters =
    esp32_exception_decoder
    time

board_build.filesystem = littlefs
board_build.cppstd = c++17
build_unflags = -std=gnu++11
build_flags =
extra_scripts =
    pre:build-scripts/inject_version.py

lib_deps =
    fastled/FastLED@^3.10.1
    thijse/ArduinoLog@^1.1.1
    https://github.com/lacamera/ESPAsyncWebServer.git#3.1.0

; ----------------------------------------------------------------
; VARIANTS
; ----------------------------------------------------------------

; 1. ESP32-WROOM (The Classic)
[env:esp32_wroom]
board = esp32dev
build_flags =
	${env.build_flags}
    -DESP32_WROOM

; 2. ESP32-S3-Zero (Waveshare/Similar)
[env:esp32_s3_zero]
board = esp32-s3-devkitc-1
build_flags =
	${env.build_flags}
    -DESP32_S3
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1 ; Ensures Serial works over the USB-C port

; 3. ESP32-C3-Zero (Waveshare/Similar)
[env:esp32_c3_zero]
board = esp32-c3-devkitm-1
build_flags =
	${env.build_flags}
    -DESP32_C3
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1 ; Ensures Serial works over the USB-C port
