import numpy as np
import led_utils

CORNER_BUFFER = 5  # 5mm gap at corners

class Rect:
    def __init__(self, name, width_cm, height_cm, led_per_m, origin_offset=(0,0)):
        self.name = name
        self.width_mm = width_cm * 10.0
        self.height_mm = height_cm * 10.0
        self.pitch = 1000.0 / led_per_m
        self.offset = np.array(origin_offset)

        # Calculate LED counts based on physical length
        # We assume the strip covers the length minus the corner buffers
        # Rounding to nearest int to match physical LED strip cutting points
        self.leds_x = int(round(self.width_mm * (led_per_m / 1000.0)))
        self.leds_y = int(round(self.height_mm * (led_per_m / 1000.0)))

        # For the L10 specifically, we want to preserve the legacy count if it differs
        if name == "L10":
            self.leds_x = 13
            self.leds_y = 13

    def generate(self):
        """
        Generates coordinates for a generic rectangle.
        Returns: (flat_coordinates, segment_counts)
        """
        # Physical width/height used for coordinate placement
        # We calculate exact start/end points based on pitch and count to center the strip
        span_x = (self.leds_x - 1) * self.pitch
        span_y = (self.leds_y - 1) * self.pitch

        half_w = span_x / 2 + CORNER_BUFFER
        half_h = span_y / 2 + CORNER_BUFFER

        # Top (Right->Left), Left (Top->Bottom), Bottom (Left->Right), Right (Bottom->Top)
        # We define (Start, End) for each side
        sides_defs = [
            # Top: y is constant positive, x changes
            ((half_w - CORNER_BUFFER, half_h), (-half_w + CORNER_BUFFER, half_h), self.leds_x),
            # Left: x is constant negative, y changes
            ((-half_w, half_h - CORNER_BUFFER), (-half_w, -half_h + CORNER_BUFFER), self.leds_y),
            # Bottom: y is constant negative, x changes
            ((-half_w + CORNER_BUFFER, -half_h), (half_w - CORNER_BUFFER, -half_h), self.leds_x),
            # Right: x is constant positive, y changes
            ((half_w, -half_h + CORNER_BUFFER), (half_w, half_h - CORNER_BUFFER), self.leds_y),
        ]

        all_coords = []
        counts = []

        for start, end, count in sides_defs:
            # Generate points
            segment = np.linspace(start, end, count)
            # Apply global offset (for nested rectangles)
            segment = segment + self.offset
            all_coords.append(segment)
            counts.append(count)

        return np.vstack(all_coords), counts

def main():
    # --- Configuration ---

    # 1. L10: Original 10cm Square (144 LED/m)
    l10 = Rect("L10", width_cm=10, height_cm=10, led_per_m=144)

    # 2. L25: 25cm Square (60 LED/m)
    l25 = Rect("L25", width_cm=25, height_cm=25, led_per_m=60)

    # 3. L70: Composite of two rectangles (Outer 50x70, Inner 40x60)
    # Both 60 LED/m. Inner is centered (0,0).
    l70_outer = Rect("L70_Outer", width_cm=70, height_cm=50, led_per_m=60)
    l70_inner = Rect("L70_Inner", width_cm=60, height_cm=40, led_per_m=60)

    models = {
        "L10": [l10],
        "L25": [l25],
        "L70": [l70_outer, l70_inner] # Processed in order: Outer ring first, then Inner
    }

    # --- Generation & Printing ---

    print("// Auto-generated LED coordinates for L-Family")
    print("// Generated by L_family.py\n")

    for model_name, rects in models.items():
        print(f"// --- Model: {model_name} ---")

        full_coords = []
        full_counts = []

        for r in rects:
            coords, counts = r.generate()
            full_coords.extend(coords)
            full_counts.extend(counts)

        # variable name e.g., "coords_L70"
        var_name = f"coords_{model_name}"

        led_utils.print_arduino_header(full_coords, variable_name=var_name, row_counts=full_counts)
        led_utils.print_bounding_box(full_coords)
        print("\n" + "-"*40 + "\n")

if __name__ == "__main__":
    main()